//array containing all files needed for the project
const batches = [
        ["U6IHouoVj-c", "batch_1/a.jpg", "batch_1/b.jpg", "batch_1/c.jpg"],
        ["batch_2/a.jpg", "batch_2/b.jpg", "batch_2/c.jpg", "batch_2/d.jpg"],
        ["batch_3/a.jpg", "batch_3/b.jpg", "batch_3/c.jpg", "batch_3/d.jpg", "batch_3/e.jpg", "batch_3/f.jpg"],
        ["batch_4/a.jpg", "batch_4/b.jpg", "batch_4/c.jpg"],
        ["batch_5/a.jpg", "batch_5/b.jpg", "batch_5/c.jpg", "batch_5/d.jpg"],
        ["batch_6/a.jpg", "batch_6/b.jpg", "batch_6/c.jpg", "batch_6/d.jpg", "batch_6/e.jpg", "batch_6/f.jpg"],
        ["batch_7/a.jpg", "batch_7/b.jpg", "batch_7/c.jpg", "batch_7/d.jpg", "batch_7/e.jpg", "batch_7/f.jpg"],
        ["batch_8/b.jpg", "batch_8/c.jpg", "batch_8/d.jpg"],
        ["batch_9/a.jpg", "batch_9/b.jpg", "batch_9/c.jpg", "batch_9/d.jpg", "batch_9/e.jpg", "batch_9/f.jpg", "batch_9/g.jpg"],
        ["batch_10/a.jpg", "batch_10/b.jpg", "batch_10/c.jpg", "batch_10/d.jpg"],
        ["batch_11/a.jpg", "batch_11/b.jpg", "batch_11/c.jpg", "batch_11/d.jpg", "batch_11/e.jpg"],
        ["Csh3CxPDksE", "batch_12/a.jpg", "batch_12/b.jpg", "batch_12/c.jpg"],
        ["batch_13/a.jpg", "batch_13/b.jpg", "batch_13/c.jpg", "batch_13/d.jpg", "batch_13/e.jpg"],
        ["batch_14/a.jpg", "batch_14/b.jpg", "batch_14/c.jpg", "batch_14/d.jpg", "batch_14/e.jpg"],
        ["batch_15/a.jpg", "batch_15/b.jpg", "batch_15/c.jpg", "batch_15/d.jpg"],
        ["batch_16/a.jpg", "batch_16/b.jpg"],
        ["batch_17/a.jpg", "batch_17/b.jpg", "batch_17/c.jpg", "batch_17/d.jpg", "batch_17/e.jpg"],
        ["batch_18/a.jpg", "batch_18/b.jpg", "batch_18/c.jpg", "batch_18/d.jpg"],
        ["batch_19/a.jpg"],
        ["batch_20/a.jpg", "batch_20/b.jpg", "batch_20/c.jpg"],
        ["batch_21/a.jpg", "batch_21/b.jpg", "batch_21/c.jpg", "batch_21/d.jpg"],
        ["ALtUEjiMb4Q", "batch_22/a.jpg"],
        ["Nve0dbr0pzw", "batch_23/a.jpg", "batch_23/b.jpg", "batch_23/c.jpg"]        
];